edition: 3.0.0
name: test-node-app 
access: quanxi

vars:
  region: ${env('REGION', 'cn-hongkong')}

resources:
  fcDemo:
    component: ${env('fc_component_version', path('../../../'))}
    props:
      region: ${vars.region}
      functionName: fc3-event-${env('fc_component_function_name', 'nodejs18')}-ossConfig
      role: acs:ram::${config('AccountID')}:role/aliyunaliyunfcdefaultrole
      runtime: ${env('fc_component_runtime', 'nodejs18')}
      code: './test-auto-code'
      handler: index.handler
      memorySize: 128
      timeout: 60
      ossMountConfig: auto

  fcDemo2: # 业务名称/模块名称
    component: ${env('fc_component_version', path('../../../'))}
    props: # 组件的属性值
      region: ${vars.region}
      functionName: fc3-event-${env('fc_component_function_name', 'nodejs18')}-ossConfigF2
      role: acs:ram::${config('AccountID')}:role/aliyunaliyunfcdefaultrole
      runtime: ${env('fc_component_runtime', 'nodejs18')}
      code: ./test-auto-code
      handler: index.handler
      memorySize: 128
      timeout: 60
      ossMountConfig: auto|rules=[{"allowedOrigin":"*","allowedMethod":"GET","allowedHeader":"*","exposeHeader":"Content-Length","maxAgeSeconds":30}]