name: macos docker (build and local) ci

on:
  push:
    branches:
      - master

env:
  REGION: cn-hongkong

jobs:
  docker-ci:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: install s
        run: |
          npm i @serverless-devs/s -g
      - name: config s
        run: |
          s config add --AccountID  ${{secrets.ACCOUNTID}} --AccessKeyID ${{secrets.ACCESSKEYID}} --AccessKeySecret ${{secrets.ACCESSKEYSECRET}} -a quanxi -f
      - name: Configure NPM
        run: |
          npm config set registry https://registry.npmjs.org
          npm config set '//packages.aliyun.com/670e108663cd360abfe4be65/npm/npm-registry/:_authToken' ${{secrets.NPM_TOKEN}}
      - name: NPM  install
        run: |
          npm install
      - name: NPM run build
        run: |
          npm run build
      - name: test python
        run: |
          cd __tests__/e2e/python && ./run && cd -
      - name: test nodejs
        run: |
          cd __tests__/e2e/nodejs && ./run && cd -
      - name: test golang
        run: |
          cd __tests__/e2e/go && ./run && cd -
      - name: test php
        run: |
          cd __tests__/e2e/php && ./run && cd -
      - name: test java
        run: |
          cd __tests__/e2e/java && ./run && cd -
      - name: test dotnetcore
        run: |
          cd __tests__/e2e/dotnetcore && ./run && cd -
      - name: test apt
        run: |
          cd __tests__/e2e/apt && ./run && cd -
      - name: test custom.debian10
        run: |
          cd __tests__/e2e/custom.debian10 && ./run && cd -
      - name: test custom
        run: |
          cd __tests__/e2e/custom && ./run && cd -
      - name: test custom container
        run: |
          cd __tests__/e2e/custom-container && ./run && cd -
      - name: test local with nas 
        run: |
          cd __tests__/e2e/local && sudo ./run && cd -
      - name: test custom.debian11
        run: |
          cd __tests__/e2e/custom.debian11 && ./run && cd -